### ISSUE TITLE
cask package name

### ISSUE THREAD

**Issue by AlJohri** [iterative/homebrew-dvc#11]
Is this line correct? 

https://github.com/iterative/homebrew-dvc/blob/c87fef79a8f9f8f50a18cebb412a88e5e55679a3/Casks/dvc.rb#L10

```
$ pkgutil --packages | grep dvc
com.iterative.dvc
```

**Comment by efiop** [comment]
Great point! It is a bug. Will fix it ASAP. Thanks a lot for the feedback!
