### ISSUE TITLE
dvc cask upgrade notice

### ISSUE THREAD

**Issue by AlJohri** [iterative/homebrew-dvc#14]
I find the dvc cask release slightly lags the other releases so I find myself always at least one minor version behind. This makes it so all `dvc` commands output this message:

```
+-------------------------------------------+
|                                           |
|     Update available 0.54.1 -> 0.55.0     |
|         Run brew cask upgrade dvc         |
|                                           |
+-------------------------------------------+
```

This is slightly related to https://github.com/iterative/dvc/issues/1894

I don't mind updating, even frequently for minor updates; however, the cask doesn't exist when it asks me to update due to the lagged release.

And because of the frequent releases combined with the lagged cask release, this message stays forever. 💀 

Is there anyway to tighten the release lag to ensure this message only prompts when the cask exists?

**Comment by efiop** [comment]
@AlJohri Hm, how long is the lag? We update the cask at the same time as we update lambda(which is where dvc gets the notice from), even slightly later than lambda. It should be available instantly. Maybe you need to run something like `brew cask update`?

**Comment by AlJohri** [comment]
Ah yes thanks, I think you are right. I disabled brew auto update (`export HOMEBREW_NO_AUTO_UPDATE=1`) and this is what I get...

Perhaps the messaging can be changed to `brew update && brew cask upgrade dvc`?
But this is fairly minor. Thanks!

p.s. `brew cask update` is deprecated / doesn't work

**Comment by efiop** [comment]
@AlJohri Sounds good, please feel free to send a PR https://github.com/iterative/dvc/blob/0a837eadfc2217e3dfefa36ad3f9c0176c9c7759/dvc/updater.py#L123 :slightly_smiling_face:
