### ISSUE TITLE
dvc 2.10.x fail to build

### ISSUE THREAD

**Issue by pmrowla** [iterative/homebrew-dvc#50]
The issue is that the wheel for `aliyun-python-sdk-core-v3==3.13.31` fails to build, so the entire pipgrip (python dep resolver used by homebrew) call fails when it has to iterate over all versions of `aliyun-python-sdk-core-v3` which are allowed by `oss2` (via `ossfs`)

```
python -m pip wheel --no-deps --disable-pip-version-check --wheel-dir /tmp/test-pipgrip aliyun-python-sdk-core-v3==2.13.31
Collecting aliyun-python-sdk-core-v3==2.13.31
  Using cached aliyun-python-sdk-core-v3-2.13.31.tar.gz (440 kB)
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package aliyun-python-sdk-core-v3 produced metadata for project name aliyun-python-sdk-core. Fix your #egg=aliyun-python-sdk-core-v3 fragments.
Discarding https://files.pythonhosted.org/packages/13/63/52c2fc00ce2334cef2051548215ae27878b187b819f01876539608752837/aliyun-python-sdk-core-v3-2.13.31.tar.gz#sha256=427f27f420d3d88577788f703e2ee1b2f804e9ce645a2e175dafe9c56d339b3c (from https://pypi.org/simple/aliyun-python-sdk-core-v3/): Requested aliyun-python-sdk-core from https://files.pythonhosted.org/packages/13/63/52c2fc00ce2334cef2051548215ae27878b187b819f01876539608752837/aliyun-python-sdk-core-v3-2.13.31.tar.gz#sha256=427f27f420d3d88577788f703e2ee1b2f804e9ce645a2e175dafe9c56d339b3c has inconsistent name: filename has 'aliyun-python-sdk-core-v3', but metadata has 'aliyun-python-sdk-core'
ERROR: Could not find a version that satisfies the requirement aliyun-python-sdk-core-v3==2.13.31 (from versions: 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.7.2, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.8.7, 2.8.8, 2.8.9, 2.9.0, 2.9.1, 2.9.3, 2.9.4, 2.10.1, 2.11.0, 2.11.1, 2.11.4, 2.11.5, 2.12.1, 2.13.0, 2.13.3, 2.13.8, 2.13.9, 2.13.10, 2.13.11, 2.13.31, 2.13.32, 2.13.33)
ERROR: No matching distribution found for aliyun-python-sdk-core-v3==2.13.31
```

The reason it has to iterate over all the versions in the first place is that aliyun requires `jmespath<1.0.0`, but by default pipgrip initially selects `jmespath==1.0.0` via `knack` (from DVC's `azure` dependencies).

The workaround for this is to force pipgrip to check `jmespath<1.0.0` or `aliyun-python-sdk-core-v3!=2.13.31`, but there is no way to pass specific extras into the brew python utilities (`brew update-python-resources` and `brew bump-formula-pr`), so I think we will probably have to explicitly specify one or the other (either in the `dvc[azure]` extra or `dvc[oss]` extra).

**Comment by pmrowla** [comment]
I opened a pipgrip issue since ideally this would just be handled in homebrew's dep resolver https://github.com/ddelange/pipgrip/issues/77

**Comment by ddelange** [comment]
Not something to rely on, but: if dvc mentions `ossfs` *before* `knack`, pipgrip will go down a different path as `jmespath<1.0.0` is encountered before unpinned `jmespath`, and this happens to succeed :)

For the determinists, would it help if pipgrip looked for an environment variable containing additional requirements split by space?

e.g.
```console
$ export PIPGRIP_ADDITIONAL_REQUIREMENTS='aliyun-python-sdk-core-v3!=2.13.31'
$ pipgrip --tree knack oss2
knack (0.9.0)
├── argcomplete (2.0.0)
├── jmespath (0.10.0)
├── pygments (2.11.2)
├── pyyaml (6.0)
└── tabulate (0.8.9)
oss2 (2.15.0)
├── aliyun-python-sdk-core>=2.13.12 (2.13.36)
│   ├── cryptography>=2.6.0 (36.0.2)
│   │   └── cffi>=1.12 (1.15.0)
│   │       └── pycparser (2.21)
│   └── jmespath<1.0.0,>=0.9.3 (0.10.0)
├── aliyun-python-sdk-kms>=2.4.1 (2.15.0)
│   └── aliyun-python-sdk-core>=2.11.5 (2.13.36)
│       ├── cryptography>=2.6.0 (36.0.2)
│       │   └── cffi>=1.12 (1.15.0)
│       │       └── pycparser (2.21)
│       └── jmespath<1.0.0,>=0.9.3 (0.10.0)
├── crcmod>=1.7 (1.7)
├── pycryptodome>=3.4.7 (3.14.1)
├── requests!=2.9.0 (2.27.1)
│   ├── certifi>=2017.4.17 (2021.10.8)
│   ├── charset-normalizer~=2.0.0 (2.0.12)
│   ├── idna<4,>=2.5 (3.3)
│   └── urllib3<1.27,>=1.21.1 (1.26.9)
└── six (1.16.0)
aliyun-python-sdk-core-v3!=2.13.31 (2.13.33)
├── cryptography>=2.6.0 (36.0.2)
│   └── cffi>=1.12 (1.15.0)
│       └── pycparser (2.21)
└── jmespath<1.0.0,>=0.9.3 (0.10.0)
```

**Comment by pmrowla** [comment]
> For the determinists, would it help if pipgrip looked for an environment variable containing additional requirements split by space?

This would work for our purposes since it would get around the issue of not being able to pass specific dep/version information through the homebrew utilities all the way into pipgrip

**Comment by pmrowla** [comment]
Fixing the automated build again can be done once the linked PR gets merged in Homebrew/brew

---

2.10.1 also requires adding `bcrypt` to the brew extras (see https://github.com/iterative/dvc/issues/7569) which can't be done via the automated bump script, manual PR is here: https://github.com/Homebrew/homebrew-core/pull/99342
