### ISSUE TITLE
brew package depends on python@3.11 instead of 3.10

### ISSUE THREAD

**Issue by pmrowla** [iterative/homebrew-dvc#92]
https://github.com/Homebrew/homebrew-core/blob/c8c39438f9d3a4121964355a7e3f47a4c40af0f8/Formula/dvc.rb#L31

The DVC brew formula currently depends on `python@3.11`, I think this happened as a blanket/general update of all python brew packages once they added support for 3.11. However, hydra doesn't support 3.11 so any hydra related experiments functionality (`exp run --set-param` in particular) is unusable in the current brew package.

We will need to send a PR updating the DVC formula to use `depends on python@3.10`. I think this will also require updating the formula to use a 3.10 virtualenv (instead of the default brew python path), see examples on how to handle this here: https://github.com/Homebrew/homebrew-core/issues/108008

**Comment by skshetry** [comment]
Hydra might get released soon with the support. Main branch already has the support. So i think it’s better to just wait.

**Comment by skshetry** [comment]
This should hopefully be fixed in 2.37.0 release.
